Problem 1: Create a 1D Numpy array of numbers from 0 to 20

In [2]:
import numpy as np

In [ ]:
numbers= np.array(range(0,21))
print(numbers)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Problem 2: Create a 3x3 identity matrix

In [ ]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Problem 3: Create a 2x2 matric and perform addition,subtraction and multiplication

In [ ]:
x = np.random.randint(2,10,(2,2))
y = np.random.randint(2,10,(2,2))
print(x)
print(y)

[[9 5]
 [7 8]]
[[9 8]
 [9 7]]


In [ ]:
addition = x+y
Subtraction = x-y
multiplication = x*y
print(addition)
print(Subtraction)
print(multiplication)

[[18 13]
 [16 15]]
[[ 0 -3]
 [-2  1]]
[[81 40]
 [63 56]]


In [ ]:
transpose = x.T
print(transpose)


[[9 7]
 [5 8]]


Problem 4: Create a numpy array of 20 random integers from 1-100, find the mean , median and standard deviation


In [ ]:
array = np.random.randint(1,100,20)
print(array)

[55 64 69 75  3  2 47 42  6 63 48 88 78 78 59 90 85 43 46 44]


In [ ]:
array_mean = np.mean(array)
array_median = np.median(array)
array_std = np.std(array)
print("mean:",array_mean)
print("median:",array_median)
print("standard deviation:",array_std)


mean: 54.25
median: 57.0
standard deviation: 26.038193101672782


Problem 5: Reshape a 1D array of size 12 into  3x4

In [ ]:
one_dimension= np.random.randint(1,20,12)
print(one_dimension)
print(one_dimension.size)


[ 5  3 13  7 15 17  8  8 13  5  6  8]
12


In [ ]:
new_array = one_dimension.reshape(3,4)
print(new_array)
print(new_array.shape)

[[ 5  3 13  7]
 [15 17  8  8]
 [13  5  6  8]]
(3, 4)


Problem 6: Extract all even numbers from a numpy array

In [ ]:
x=np.random.randint(1,20,10)
print("Original array:", x)
even_numbers = x[x % 2 == 0]
print("Even numbers:", even_numbers)

Original array: [17 12 19  6 18 14  9 12 12 10]
Even numbers: [12  6 18 14 12 12 10]


Problem 7: Create a 5x5 matrix with values 1 to 25 and slice the middle 3x3 submatrix

In [ ]:
matrix_5x5 = np.random.randint(1,26,(5,5))
print(matrix_5x5)

[[ 6 11  1  3 20]
 [14 24  9  9 20]
 [ 4 12 25 18  6]
 [14 15  2  6 17]
 [24  6 17 17  7]]


In [ ]:
submatrix_3x3 = matrix_5x5[1:4,1:4]
print(submatrix_3x3)

[[24  9  9]
 [12 25 18]
 [15  2  6]]


Problem 8: Simulate 1000 coin flips(0=head, 1=tail) find probabilty of head

In [ ]:
coin_flips = np.random.randint(0,2,1000)
print(coin_flips)
head_count = np.sum(coin_flips == 0)
prob_head = head_count/1000
print("Number of heads:",head_count)
print("Probability of head:",round(prob_head,1))

[1 1 1 1 0 0 1 1 1 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 1 1
 1 0 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 1 1 1 0 0 1 0
 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 1 0 1 1
 1 0 1 1 0 1 0 1 0 1 0 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 1 1 1 0 0
 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1
 0 0 0 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 0 0 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 0
 1 1 1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 0 0
 0 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 1 0 1 0 1 1 1 0 0 0 0 0 1 1 0
 0 1 0 1 0 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 1
 1 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1 0 0 0 1 1 0 1 0 1 1 1 1 1 1 1 1
 0 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0
 0 0 1 1 0 0 0 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 1 1 1
 0 0 1 0 1 0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 1 1 1 1 1 1 0 1 0 1 1 

Problem 9: Solve a system of linear equations using np.linalg.solve()

In [ ]:
#EXAMPLE 1
A = np.array([[3, 2], [1, -4]])
b = np.array([12, -2])
print(A)
print(b)

[[ 3  2]
 [ 1 -4]]
[12 -2]


In [ ]:
solution = np.linalg.solve(A, b)

# Print the solution
print("Solution:", solution)

Solution: [3.14285714 1.28571429]


In [ ]:
#Example 2
A = np.array([[1,2,3], [2,-1,1],[3,1,-1]])
b = np.array([14, 3,5])
print(A)
print(b)

[[ 1  2  3]
 [ 2 -1  1]
 [ 3  1 -1]]
[14  3  5]


In [ ]:
solution = np.linalg.solve(A, b)

# Print the solution
print("Solution:", solution)

Solution: [1.6 2.6 2.4]


Problem 10: Normalize a numpy array so all values are between 0 and 1

In [7]:
"""creating a numpy array"""
array = np.random.randint(1,20,10)
print(array)
"""normalizing the array using the formula"""
normalized_array = (array - array.min()) / (array.max() - array.min())
print(new_array)


[ 8 10  1  1  2  5  7  8  1  9]
[0.11111111 0.98888889 0.         0.78888889 0.07777778 0.43333333
 0.18888889 1.         0.04444444 0.24444444]
